version: '3'

volumes:
  docker-ruby-db:

services:
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - ".:/docker-ruby"
    tty: true
    stdin_open: true
    environment:
      - "DATABASE_PASSWORD=postgres"
      
    depends_on:
      - db
    links:
      - db

  db:
    image: postgres:18
    volumes:
      - "docker-ruby-db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=postgres"